### ISSUE TITLE
Already registered Julia package with name `Rotations`

### ISSUE THREAD

**Issue by han-so1omon** [ronisbr/ReferenceFrameRotations.jl#2]
Prevents easy installation of package. Perhaps change the name to `rotations` or `JuliaRotations`.

**Comment by ronisbr** [comment]
Hi @han-so1omon ,

Actually, I have never though about turning this into an official Julia package. However, a developer of Julia told me that a new packaging system is coming, and, in this case, it will be possible to have packages from different developers with the same name. I will investigate about it. If it does not work that way, I will change the name as you suggested :)

**Comment by ronisbr** [comment]
Hi @han-so1omon,

Following your advice, this package was renamed to `ReferenceFrameRotations` and was submitted to official Julia repository:

https://github.com/JuliaLang/METADATA.jl/pull/14441

Thanks!
